name: Setup KernelSU-Next

on:
  workflow_dispatch:  # Memungkinkan workflow dijalankan secara manual

jobs:
  setup:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Memberikan akses write ke repository

    steps:
    - name: Install KernelSU-Next
      run: |
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
